name: iOS Release
on: workflow_dispatch

permissions: write-all

jobs:
  iOS:
     runs-on: macos-13
     steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5

      - name: Restore existing build cache for faster compilation
        if: inputs.name == 'iOS'
        uses: actions/cache@v4
        with:
          # not caching the bin folder to prevent asset duplication and stuff like that
          key: cache-build-ios
          path: |
            .haxelib/
            export/release/ios/PibbyApocalypse/haxe/
          restore-keys: |
            cache-build-ios
            

      - name: Install Libraries
        run: |
          haxelib install hmm --quiet
          haxelib run hmm install --quiet
        # haxelib run lime rebuild extension-iostools ios -arm64 -final

      - name: Clearing already existing cache
        if: inputs.name == 'iOS'
        uses: actions/github-script@v6
        with:
          script: |
            const caches = await github.rest.actions.getActionsCacheList({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            for (const cache of caches.data.actions_caches) {
              if (cache.key == "cache-build-ios") {
                console.log('Clearing ' + cache.key + '...')
                await github.rest.actions.deleteActionsCacheById({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  cache_id: cache.id,
                })
                console.log("Cache cleared.")
              }
            }

    # sb 报错666

      # - name: Install MobileVLCKit Framework
        # run: |
          # cd ${{ github.workspace }}/..
          # wget -q https://download.videolan.org/cocoapods/prod/MobileVLCKit-3.5.1-34408b84-e9eceaed.tar.xz
          # tar -xf MobileVLCKit-3.5.1-34408b84-e9eceaed.tar.xz

      - name: Compile
        run: haxelib run lime build ios -nosign -D -final

      # - name: Check Code Signing
        # run: cd export/release/ios/build/Release-iphoneos && codesign -dv *.app

      - name: Make Ipa
        run: |
          cd export/release/ios/build/Release-iphoneos
          mkdir Payload
          mv *.app Payload
          zip -r Pibby：Apocalypse.ipa Payload

      - name: Upload Artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@main
        with:
          name: iOSBuild
          path: export/release/ios/build/Release-iphoneos/*.ipa
          if-no-files-found: error

      - name: Uploading new cache
        if: inputs.name == 'iOS'
        uses: actions/cache@v4
        with:
          # caching again since for some reason it doesnt work with the first post cache shit
          key: cache-build-ios
          path: |
            .haxelib/
            export/release/ios/PibbyApocalypse/haxe/
          restore-keys: |
            cache-build-ios
