name: iOS Release
on: workflow_dispatch
jobs:
  iOS:
     runs-on: macos-15
     steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7

      - name: Install Libraries
        run: |
          haxelib setup ~/haxelib
          haxelib git hxcpp https://github.com/th2l-devs/hxcpp --quiet
          haxelib install lime 8.2.0 --quiet
          haxelib install openfl 9.3.3 --quiet
          haxelib --never install flixel 5.8.0 --quiet
          haxelib run lime setup flixel --quiet
          haxelib install flixel-tools --quiet
          haxelib install flixel-ui --quiet
          haxelib install flixel-addons 3.2.2 --quiet
          haxelib install tjson --quiet
          haxelib install hxjsonast --quiet
          haxelib install hscript --quiet
          haxelib git hxCodec https://github.com/JuniorNovoa1/hxCodec-2.5.1-MacOS-Support --quiet
          haxelib git linc_luajit https://github.com/th2l-devs/linc_luajit.git --quiet
          haxelib install hxcpp-debug-server --quiet
          haxelib list
        # haxelib run lime rebuild extension-iostools ios -arm64 -final

      - name: Setup Lime
        run: |
          haxelib set lime 8.2.0
          haxelib set openfl 9.2.1
          haxelib set flixel 5.2.2
          haxelib set hxCodec 2.5.1
          haxelib set flixel-addons 3.0.2
          haxelib set hxcpp git
    # sb 报错666

      # - name: Install MobileVLCKit Framework
        # run: |
          # cd ${{ github.workspace }}/..
          # wget -q https://download.videolan.org/cocoapods/prod/MobileVLCKit-3.5.1-34408b84-e9eceaed.tar.xz
          # tar -xf MobileVLCKit-3.5.1-34408b84-e9eceaed.tar.xz

      - name: Compile
        run: haxelib run lime build ios -nosign -D -final

      # - name: Check Code Signing
        # run: cd export/release/ios/build/Release-iphoneos && codesign -dv *.app

      - name: Make Ipa
        run: |
          cd export/release/ios/build/Release-iphoneos
          mkdir Payload
          mv *.app Payload
          zip -r Pibby：Apocalypse.ipa Payload

      - name: Upload Artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@main
        with:
          name: iOSBuild
          path: export/release/ios/build/Release-iphoneos/*.ipa
          if-no-files-found: error
