name: Release
on: workflow_dispatch
jobs:
  iOS:
     runs-on: macos-13
     steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1.2.0
        with:
          haxe-version: 4.2.5

      - name: Install Libraries
        run: |
          haxelib setup ~/haxelib
          haxelib git hxcpp https://github.com/th2l-devs/hxcpp
          haxelib install lime 8.0.1
          haxelib install openfl 9.2.1
          haxelib --never install flixel 5.2.2
          haxelib run lime setup flixel
          haxelib install flixel-tools
          haxelib install flixel-ui
          haxelib install flixel-addons 3.0.2
          haxelib install tjson
          haxelib install hxjsonast
          haxelib install hscript
          haxelib install hxCodec 2.6.1
          haxelib git linc_luajit https://github.com/superpowers04/linc_luajit.git
          haxelib install hxcpp-debug-server
          haxelib list
          haxelib run lime rebuild extension-iostools ios -arm64 -final

      - name: Setup Lime
        run: |
          haxelib set lime 8.0.1
          haxelib set openfl 9.2.1
          haxelib set flixel 5.2.2
          haxelib set hxCodec 2.5.1
          haxelib set flixel-addons 2.11.0
          haxelib set hxcpp git
    # sb 报错666

      # - name: Install MobileVLCKit Framework
        # run: |
          # cd ${{ github.workspace }}/..
          # wget -q https://download.videolan.org/cocoapods/prod/MobileVLCKit-3.5.1-34408b84-e9eceaed.tar.xz
          # tar -xf MobileVLCKit-3.5.1-34408b84-e9eceaed.tar.xz

      - name: Compile
        run: haxelib run lime build ios -D -final

      # - name: Check Code Signing
        # run: cd export/release/ios/build/Release-iphoneos && codesign -dv *.app

      - name: Make Ipa
        run: |
          cd export/release/ios/build/Release-iphoneos
          mkdir Payload
          mv *.app Payload
          zip -r Pibby：Apocalypse.ipa Payload

      - name: Upload Artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@main
        with:
          name: iOSBuild
          path: export/release/ios/build/Release-iphoneos/*.ipa
          if-no-files-found: error
